"""
SU2 Batch Runner — tuned for turb_SA_RAE2822.cfg
Generates one config per AoA, runs SU2_CFD in parallel, collects surface CSVs.

Usage
-----
1. Put this script in the same folder as your .cfg and .su2 files
2. Edit the USER SETTINGS section below
3. Run:  python su2_batch_runner.py
"""

import re
import shutil
import subprocess
import concurrent.futures
from pathlib import Path
import numpy as np
import csv
import vtk
from vtkmodules.util.numpy_support import numpy_to_vtk, vtk_to_numpy

# ── USER SETTINGS ─────────────────────────────────────────────────────────────

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent

BASE_CONFIG = SCRIPT_DIR / "turb_SA_RAE2822.cfg"      # your base config (do not edit this file)
MESH_FILE   = SCRIPT_DIR / "mesh_RAE2822_turb.su2"    # must be in the same folder as this script
MESH_NAME   = MESH_FILE.name
SU2_BIN     = "D:/SU2/bin/SU2_CFD"                    # or full path e.g. "/usr/local/bin/SU2_CFD"
OUTPUT_DIR  = PROJECT_ROOT / "data" / "batch_su2_cases"  # all case folders go here

# ── AoA values to generate ────────────────────────────────────────────────────
# Current dataset: integers 0-20 (21 cases)
# Adding half-degree steps around the problem zone (11-13 deg) and boundaries

AOA_VALUES = [
    # Dense sampling around regime transition (your high-RMSE zone)
    # 1,
    10.25, 10.5, 10.75,
    11.25, 11.5, 11.75,
    12.25, 12.5, 12.75,
    13.25, 13.5, 13.75,
    # Extra boundary coverage (your other high-RMSE zone)
    # -1.0, -0.5, 
    0.5,
    # Mid-range extras if you want even denser coverage
    1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5,
]

# Parallel workers — set to number of CPU cores you want to use.
# Each SU2 job runs single-threaded, so MAX_WORKERS = number of cores is fine.
# If you use MPI per job (e.g. mpirun -n 4), set MAX_WORKERS = total_cores / 4
MAX_WORKERS = 4

# MPI command — set to None for single-threaded, or e.g. ["mpirun", "-n", "4"]
MPI_CMD = None

# ── INTERNALS (no need to edit below) ─────────────────────────────────────────

def convert_vtu_to_csv(vtu_file: str, csv_file: str):
    reader = vtk.vtkXMLUnstructuredGridReader()
    reader.SetFileName(vtu_file)
    reader.Update()
    grid = reader.GetOutput()

    pd = grid.GetPointData()   # point-centred fields (Cp, pressure, velocity…)

    # --- collect all arrays ---
    arrays = {}

    # XYZ coordinates
    pts = vtk_to_numpy(grid.GetPoints().GetData())
    arrays["x"] = pts[:, 0]
    arrays["y"] = pts[:, 1]
    if pts.shape[1] == 3:
        arrays["z"] = pts[:, 2]

    # Every named point-data array
    for i in range(pd.GetNumberOfArrays()):
        arr = pd.GetArray(i)
        name = arr.GetName()
        data = vtk_to_numpy(arr)
        if data.ndim == 1:                      # scalar
            arrays[name] = data
        else:                                   # vector/tensor → split components
            for j in range(data.shape[1]):
                arrays[f"{name}_{j}"] = data[:, j]

    # --- write CSV ---
    n_pts = pts.shape[0]
    with open(csv_file, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(arrays.keys())
        for row in zip(*arrays.values()):
            writer.writerow(row)

    print(f"Converted {vtu_file}  →  {csv_file}  ({n_pts} points)")

def set_value(cfg: str, key: str, value: str) -> str:
    """Replace a SU2 config key's value in-place."""
    pattern = rf"^({re.escape(key)}\s*=\s*).*$"
    new_cfg, n = re.subn(pattern, rf"\g<1>{value}", cfg, flags=re.MULTILINE)
    if n == 0:
        raise KeyError(f"Key '{key}' not found in config")
    return new_cfg

def prepare_case(aoa: float) -> tuple:
    """Create case directory, write patched config, symlink mesh."""
    tag      = f"{aoa:.2f}"
    case_dir = OUTPUT_DIR / f"{tag}"
    case_dir.mkdir(parents=True, exist_ok=True)

    cfg = BASE_CONFIG.read_text()

    # Only the AoA changes — everything else stays identical to your base config
    cfg = set_value(cfg, "AOA", str(aoa))
    cfg = set_value(cfg, "MUSCL_FLOW", "NO")
    cfg = set_value(cfg, "MUSCL_ADJFLOW", "NO")
    cfg = set_value(cfg, "ITER", "5000")

    # Rename outputs so cases don't overwrite each other
    cfg = set_value(cfg, "SURFACE_FILENAME",  f"surface_flow")
    cfg = set_value(cfg, "VOLUME_FILENAME",   f"flow")
    cfg = set_value(cfg, "RESTART_FILENAME",  f"restart_flow.dat")
    cfg = set_value(cfg, "CONV_FILENAME",     f"history")

    if "VOLUME_OUTPUT" not in cfg:
        cfg += "\nVOLUME_OUTPUT= (COORDINATES, PRIMITIVE, SOLUTION)\n"

    (case_dir / "config.cfg").write_text(cfg)

    # Symlink mesh (avoids duplicating large mesh files)
    mesh_link = case_dir / MESH_NAME
    if not mesh_link.exists():
        mesh_src = MESH_FILE.resolve()
        try:
            mesh_link.symlink_to(mesh_src)
        except OSError:
            shutil.copy(mesh_src, mesh_link)  # Windows fallback

    return aoa, case_dir

def run_case(args) -> dict:
    """Run SU2_CFD for one case, return result dict."""
    aoa, case_dir = args
    print(f"  [START]  AoA = {aoa:+7.2f} deg  ->  {case_dir.name}")

    cmd = ([*MPI_CMD] if MPI_CMD else []) + [SU2_BIN, "config.cfg"]

    with open(case_dir / "run.log", "w") as log:
        proc = subprocess.run(cmd, cwd=case_dir, stdout=log, stderr=subprocess.STDOUT)

    ok     = proc.returncode == 0
    status = "OK" if ok else f"FAILED ({proc.returncode})"
    print(f"  [{status:^12}]  AoA = {aoa:+7.2f} deg")

    # Find the surface CSV SU2 wrote (name depends on SU2 version)
    # Convert vtu file
    vtu_path = case_dir / "surface_flow.vtu"
    csv_path_converted = case_dir / "surface_flow.csv"
    if vtu_path.exists():
        convert_vtu_to_csv(str(vtu_path), str(csv_path_converted))
    else:
        print(f"  [WARN] VTU not found: {vtu_path}")
    csv_candidates = list(case_dir.glob("surface_flow.csv"))
    csv_path = str(csv_candidates[0]) if csv_candidates else "not found"

    return {"aoa": aoa, "status": status, "dir": str(case_dir),
            "csv": csv_path, "log": str(case_dir / "run.log")}

def main():
    print("\nSU2 Batch Runner — RAE2822 SA turbulence")
    print(f"  Config      : {BASE_CONFIG}")
    print(f"  Mesh        : {MESH_FILE}")
    print(f"  New cases   : {len(AOA_VALUES)}")
    print(f"  AoA range   : {min(AOA_VALUES):.2f} -> {max(AOA_VALUES):.2f} deg")
    print(f"  Workers     : {MAX_WORKERS}")
    print(f"  Output dir  : {OUTPUT_DIR}\n")

    for f in [BASE_CONFIG, MESH_FILE]:
        if not f.exists():
            raise FileNotFoundError(f"Required file not found: {f}")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("Preparing case directories...")
    cases = [prepare_case(aoa) for aoa in sorted(AOA_VALUES)]
    print(f"  {len(cases)} directories ready.\n")

    print(f"Running SU2_CFD with up to {MAX_WORKERS} parallel workers...\n")
    results = []
    with concurrent.futures.ProcessPoolExecutor(max_workers=MAX_WORKERS) as pool:
        for r in pool.map(run_case, cases):
            results.append(r)

    ok_cases     = [r for r in results if r["status"] == "OK"]
    failed_cases = [r for r in results if r["status"] != "OK"]

    print(f"\n{'─'*55}")
    print(f"  Done: {len(ok_cases)} succeeded, {len(failed_cases)} failed")
    if failed_cases:
        print("\n  Failed cases (check run.log for details):")
        for r in failed_cases:
            print(f"    AoA = {r['aoa']:+.2f} deg  ->  {r['log']}")
    print(f"{'─'*55}\n")

    # Write summary CSV — useful for quickly loading all new surface files
    summary = OUTPUT_DIR / "batch_summary.csv"
    with open(summary, "w") as f:
        f.write("AoA,Status,SurfaceCSV,Log\n")
        for r in sorted(results, key=lambda x: x["aoa"]):
            f.write(f"{r['aoa']},{r['status']},{r['csv']},{r['log']}\n")
    print(f"Summary written to: {summary}")
    print("Surface CSVs are in their respective case subdirectories.\n")
    print("Tip: load them with pandas like your existing data —")
    print("     df = pd.read_csv(r['csv'])  for each row in batch_summary.csv\n")

if __name__ == "__main__":
    main()
